### PR TITLE
Grad perf

### PR DESCRIPTION
**Pull request by shportnoy**
@cth7, added relevant system performance info (slew rate, max grad strength, field strength) to data header. Also added a function "make_dict_from_header", which creates dictionaries from 'Dicom' and 'Config' header fields.

### CODE REVIEW

**Comment by cth7** [comment]
I made some style changes, to follow PEP8 style guidelines.

I also changed the variable name `G_max` to `grad_max` to remove the capitalization and be less ambiguous. Is this ok? Sorry for not asking you before making the change.

**Comment by cth7** [comment]
I tried loading a Prisma dataset that we acquired last year (2D radial phase contrast). Got a value of 36 for grad_code. Which then didn't match any of the keys in the gradient performance dictionaries. Do you know why this is?

**Comment by shportnoy** [comment]
I have no idea what that could be. Can you share the dataset with me?

**Comment by shportnoy** [comment]
No worries, that's fine.

**Review by cth7 — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
